apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: test-ananta
spec:
  selector:
    app: my-app
  ports:
    - name: app-port
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
    - name: appconfig-port
      protocol: TCP
      port: 2772
      targetPort: 2772
      nodePort: 32001
  type: NodePort
